### ISSUE TITLE
Feature Request: what networks are using a proxy

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#9]
I love the dashboard, great work Mirobi!

It would be helpful to know what networks are using a proxy (usually this would be a tor proxy). with the getnetworkinfo call the daemon returns "networks" > "proxy". "proxy" is empty if it's accessible directly, the field has an address if a proxy is in use. 

happy coding

**Comment by Mirobit** [comment]
With 47a43596bc2bdd1a9b139add0f6d224ddb9f66f1 a proxy icon should be displayed on the main page if a proxy is set. The proxy ip:port is only shown if you hover on the icon. 

I wasn't sure if setting a proxy means there can't be a local address. If that is the case then I will change the code, so that the proxy address is always displayed instead of the local address. So if you see `Unkown`, next to the proxy icon, please let me know.

**Comment by oitdmser** [comment]
I see the proxy icon as you described. On mine it says 'Unknown' next to the icon, if I mouse-over the proxy icon it shows the proxy ip:port

With bitcoind, if` proxy=` is enabled, all outgoing traffic is ran through the proxy. If `bind=ip.of.your.server` it can be reached over clearnet by other nodes. If `bind=127.0.0.1` all incoming and outgoing connections will be over TOR. I'm reasonably sure it's safe to assume that most node operators running` proxy=` will also be running `bind=127.0.0.1`. On nodes that are bound to a clearnet IP, i.e. `bind=ip.of.their.server`, no proxy is configured and `listenonion=1`, bitcoind will run all *.onion traffic through the local TOR proxy, all clearnet traffic through clearnet.

**Comment by Mirobit** [comment]
I am not sure on the status of this issue. I think BNM is displaying all the network information it can get right now.
@oitdmser please let me know if you consider this issue to be resolved.
